name: Build and Push Docker Image

on:
  push:
    tags:
      - "release-*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if tag is from docker branch
        id: check-branch
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          BRANCH=$(git branch -r --contains $TAG_NAME | grep -v "HEAD" | sed 's/^[[:space:]]*origin\///' | head -n 1)
          if [[ $BRANCH == docker-* ]]; then
            echo "is_docker_branch=true" >> $GITHUB_OUTPUT
          else
            echo "is_docker_branch=false" >> $GITHUB_OUTPUT
            echo "Tag was not created from a docker-* branch. Current branch: $BRANCH"
          fi

      - name: Extract tag version
        if: steps.check-branch.outputs.is_docker_branch == 'true'
        id: tag-version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/release-}
          echo "version=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        if: steps.check-branch.outputs.is_docker_branch == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: steps.check-branch.outputs.is_docker_branch == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get date information
        if: steps.check-branch.outputs.is_docker_branch == 'true'
        id: date
        run: |
          # Format: YYYYMMDD
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Extract metadata for Docker
        if: steps.check-branch.outputs.is_docker_branch == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/dayoneteams/odoo-community
          tags: |
            18-python3.11-${{ steps.date.outputs.date }}
            18-python3.11-${{ steps.tag-version.outputs.version }}
            18-python3.11-pg16-${{ steps.date.outputs.date }}
            18-pg16
            18
            latest

      - name: Build and push
        if: steps.check-branch.outputs.is_docker_branch == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
